name: Meander CI

on:
  push:
  pull_request:

jobs:
  jvm-clj:

    runs-on: ubuntu-latest

    container:
      image:  clojure:openjdk-11-tools-deps

    steps:
    - uses: actions/checkout@v1
    - name: Run JVM tests
      run: clojure -A:test

  jvm-clj-and-cljs-in-cp:

    runs-on: ubuntu-latest

    container:
      image:  clojure:openjdk-11-tools-deps

    steps:
    - uses: actions/checkout@v1
    - name: Run JVM tests, with clojurescript being in the classpath
      run: clojure -A:cljs:test

  cljs:

    runs-on: ubuntu-latest

    container:
      image: theasp/clojurescript-nodejs:latest

    steps:
    - uses: actions/checkout@v1
    - name: Run cljs tests
      run: clojure -A:cljs:cljs-test

  bb:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Prepare java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@7.0
      with:
        bb: latest

    - name: Run babashka tests
      run: bb test-bb
